### ISSUE TITLE
RayTracedGL1.dll 1 security vendor and no sandboxes flagged this file as malicious

### ISSUE THREAD

**Issue by Ilia-iman** [sultim-t/RayTracedGL1#26]
virustotal detects 
MaxSecure - Trojan.Malware.300983.susgen

**Comment by Andrew-Cottrell** [comment]
Related: https://github.com/sultim-t/prboom-plus-rt/issues/49#issuecomment-1122482452

If this is a false-positive, it may be reported to MaxSecure via the https://maxsecureantivirus.com/submit_aFalse_Positive.htm form.

I just checked and that link no longer works. Perhaps the https://www.maxpcsecure.com/contact.htm form is appropriate.

**Comment by sultim-t** [comment]
If you're suspicious, you can download a build from Github Actions https://github.com/sultim-t/RayTracedGL1/actions . A build is compiled on Github virtual machines, so the possibility of malware should be minimal.
