### ISSUE TITLE
HL1 Crash on multiplayer server list refresh.

### ISSUE THREAD

**Issue by xDololow** [sultim-t/RayTracedGL1#27]
So basically i dried to refresh servers and got this error.
![image](https://user-images.githubusercontent.com/26763912/221343655-e67b3b67-ffab-43e1-b04b-eacaf5fc334c.png)
![image](https://user-images.githubusercontent.com/26763912/221343664-59070e4d-d98e-411e-b8a1-849f1e88441b.png)

Couldn't reproduce.

**Comment by sultim-t** [comment]
It's related to Xash3d UI library, something got out of bounds, probably fixed in the upstream by a1batross
